CC ?= cc
CFLAGS ?= -O2 -Wall -Wextra -Wpedantic -std=c11
CPPFLAGS += -Ihde-core/include -Isrc
BUILD ?= build
CORE_SRC=hde-core/integration/core.c hde-core/settings/settings.c hde-core/session/session.c hde-core/desktop/desktop.c hde-core/panel/panel.c hde-core/notifications/notifications.c
BACKEND_SRC=backend/backend.c backend/x11/x11_backend.c backend/wayland/wayland_backend.c
CORE_OBJ=$(CORE_SRC:.c=.o) $(BACKEND_SRC:.c=.o)

GTK_CFLAGS:=$(shell pkg-config --cflags gtk+-3.0 2>/dev/null)
GTK_LIBS:=$(shell pkg-config --libs gtk+-3.0 2>/dev/null)
WNCK_CFLAGS:=$(shell pkg-config --cflags libwnck-3.0 x11 2>/dev/null)
WNCK_LIBS:=$(shell pkg-config --libs libwnck-3.0 x11 2>/dev/null)
GLIBX_CFLAGS:=$(shell pkg-config --cflags glib-2.0 x11 2>/dev/null)
GLIBX_LIBS:=$(shell pkg-config --libs glib-2.0 x11 2>/dev/null || echo "-lglib-2.0 -lX11")
# XInput2 (libxi-dev, pulled in by libgtk-3-dev): needed for the Super key to open the Start menu and for the touchpad /
# mouse settings (natural scrolling, tap to click). Without it everything still builds, just without those.
XI_CFLAGS:=$(shell pkg-config --exists xi 2>/dev/null && echo "-DHAVE_XI2 `pkg-config --cflags xi`")
XI_LIBS:=$(shell pkg-config --libs xi 2>/dev/null)
X11_LIBS:=$(shell pkg-config --libs x11 2>/dev/null || echo -lX11)
# XRandR (libxrandr-dev, pulled in by libgtk-3-dev): F8 / Super+P screen layouts (Project), screens plugged in or out,
# software brightness for F6/F7 on screens without a backlight, Night Light. Without it: none of these.
XRANDR_CFLAGS:=$(shell pkg-config --exists xrandr 2>/dev/null && echo "-DHAVE_XRANDR `pkg-config --cflags xrandr`")
XRANDR_LIBS:=$(shell pkg-config --libs xrandr 2>/dev/null)
# XFixes (libxfixes-dev, pulled in by libgtk-3-dev): the mouse pointer in screenshots (hde-screenshot --pointer)
XFIXES_CFLAGS:=$(shell pkg-config --exists xfixes 2>/dev/null && echo "-DHAVE_XFIXES `pkg-config --cflags xfixes`")
XFIXES_LIBS:=$(shell pkg-config --libs xfixes 2>/dev/null)
# gtk-layer-shell (libgtk-layer-shell-dev): the "HDE (Wayland)" session — panel, desktop, Start menu and popups as
# layer-shell surfaces. Without it HDE builds for X11 only. It must come before libwayland-client when linking.
LAYER_CFLAGS:=$(shell pkg-config --exists gtk-layer-shell-0 2>/dev/null && echo "-DHAVE_GTK_LAYER_SHELL `pkg-config --cflags gtk-layer-shell-0`")
LAYER_LIBS:=$(shell pkg-config --exists gtk-layer-shell-0 2>/dev/null && pkg-config --libs gtk-layer-shell-0)
# The panel's taskbar on Wayland: wlr-foreign-toplevel-management (protocols/), generated by wayland-scanner
# (libwayland-bin, pulled in by libgtk-3-dev / libwayland-dev).
WAYLAND_SCANNER:=$(shell pkg-config --variable=wayland_scanner wayland-scanner 2>/dev/null || command -v wayland-scanner 2>/dev/null)
WLTASK:=$(shell [ -n "$(LAYER_CFLAGS)" ] && [ -n "$(WAYLAND_SCANNER)" ] && pkg-config --exists wayland-client 2>/dev/null && echo yes)
FTM=wlr-foreign-toplevel-management-unstable-v1
ifeq ($(WLTASK),yes)
WLTASK_CFLAGS=-DHAVE_WAYLAND_TASKBAR -I$(BUILD) $(shell pkg-config --cflags wayland-client)
WLTASK_LIBS=$(shell pkg-config --libs wayland-client)
WLTASK_SRC=src/hde-wltaskbar.c $(BUILD)/$(FTM)-protocol.c
WLTASK_DEPS=$(BUILD)/$(FTM)-client-protocol.h
endif

# Flags for the GTK programs in src/
GUI_CFLAGS ?= -O2 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers
GUI_CPPFLAGS = -Isrc -DWNCK_I_KNOW_THIS_IS_UNSTABLE -DHDE_DATADIR=\"$(PREFIX)/share/hde\"

HDE_HEADERS=$(wildcard src/*.h)
PANEL_SRC=src/hde-panel.c src/hde-tray.c src/hde-status.c src/hde-osd.c src/hde-notify.c src/hde-search.c src/hde-theme.c \
          src/hde-input.c src/hde-startmenu.c src/hde-applets.c src/hde-panel-config.c src/hde-osinfo.c src/hde-svgpath.c \
          src/hde-wl.c src/hde-run.c src/hde-flyout.c src/hde-control.c src/hde-battery.c src/hde-power.c \
          src/hde-profiles.c src/hde-powersave.c src/hde-measure.c $(WLTASK_SRC)
DESKTOP_SRC=src/hde-desktop.c src/hde-theme.c src/hde-panel-config.c src/hde-wl.c
SETTINGS_SRC=src/hde-settings.c src/hde-settings-network.c src/hde-settings-bluetooth.c \
             src/hde-settings-appearance.c src/hde-settings-windows.c src/hde-settings-keyboard.c \
             src/hde-settings-sound.c src/hde-settings-touchpad.c src/hde-settings-display.c src/hde-settings-about.c \
             src/hde-theme.c src/hde-input.c src/hde-randr.c src/hde-brightness.c src/hde-sysinfo.c \
             src/hde-settings-panel.c src/hde-panel-config.c src/hde-osinfo.c src/hde-svgpath.c src/hde-wl.c \
             src/hde-settings-wayland.c src/hde-settings-power.c src/hde-power.c src/hde-profiles.c src/hde-run.c \
             src/hde-settings-peripherals.c src/hde-measure.c
# Hyggshi Files, the file manager (its own folder: hde-files/, which also has a Makefile to build it alone)
FILES_SRC=$(wildcard hde-files/src/*.c) src/hde-theme.c
# Build stamp (commit + date) shown in Settings > About, by --version and at the top of the session log, to tell at a
# glance whether the programs that run are the ones just built. Rewritten only when it changes (then only the three
# programs that show it are rebuilt). See scripts/hde-version.sh.
VERSION_H = $(BUILD)/hde-version.h

PROGRAMS=hde-session hde-desktop hde-panel hde-settings hde-hotkeys hde-xsettings hde-screenshot hde-files

all: $(BUILD)/hde-core-demo $(BUILD)/hde-session components

# The real desktop / panel / settings (GTK3) live in src/. They are built into build/ so that hde-session
# (which looks next to itself first) runs the new copies instead of falling back to old ones in /usr/local/bin.
components: $(BUILD)/hde-desktop $(BUILD)/hde-panel $(BUILD)/hde-settings $(BUILD)/hde-hotkeys $(BUILD)/hde-xsettings \
            $(BUILD)/hde-screenshot $(BUILD)/hde-files

$(BUILD)/hde-desktop: $(DESKTOP_SRC) $(HDE_HEADERS) | $(BUILD)
	$(CC) $(GUI_CFLAGS) $(GUI_CPPFLAGS) $(GTK_CFLAGS) $(LAYER_CFLAGS) -o $@ $(filter %.c,$^) $(LAYER_LIBS) $(GTK_LIBS) -lm
$(BUILD)/hde-panel: $(PANEL_SRC) $(HDE_HEADERS) $(WLTASK_DEPS) | $(BUILD)
	@[ -n "$(LAYER_CFLAGS)" ] || echo "NOTE: libgtk-layer-shell-dev (pkg-config gtk-layer-shell-0) not found: HDE for X11 only, no Wayland session"
	$(CC) $(GUI_CFLAGS) $(GUI_CPPFLAGS) $(GTK_CFLAGS) $(WNCK_CFLAGS) $(XI_CFLAGS) $(XRANDR_CFLAGS) $(LAYER_CFLAGS) \
	    $(WLTASK_CFLAGS) -o $@ $(filter %.c,$^) $(LAYER_LIBS) $(GTK_LIBS) $(WNCK_LIBS) $(XI_LIBS) $(XRANDR_LIBS) $(X11_LIBS) \
	    $(WLTASK_LIBS) -lm
$(BUILD)/$(FTM)-client-protocol.h: protocols/$(FTM).xml | $(BUILD)
	$(WAYLAND_SCANNER) client-header $< $@
$(BUILD)/$(FTM)-protocol.c: protocols/$(FTM).xml | $(BUILD)
	$(WAYLAND_SCANNER) private-code $< $@
$(BUILD)/hde-settings: $(SETTINGS_SRC) $(HDE_HEADERS) $(VERSION_H) | $(BUILD)
	@[ -n "$(XRANDR_CFLAGS)" ] || echo "WARNING: libxrandr-dev (pkg-config xrandr) not found: no F8 screen layouts, no software brightness"
	$(CC) $(GUI_CFLAGS) $(GUI_CPPFLAGS) -I$(BUILD) $(GTK_CFLAGS) $(XI_CFLAGS) $(XRANDR_CFLAGS) $(LAYER_CFLAGS) -o $@ \
	    $(filter %.c,$^) $(LAYER_LIBS) $(GTK_LIBS) $(XI_LIBS) $(XRANDR_LIBS) $(X11_LIBS) -lm
$(BUILD)/hde-hotkeys: src/hde-hotkeys.c src/hde-brightness.c src/hde-randr.c src/hde-ipc.h src/hde-commands.h \
                      src/hde-brightness.h src/hde-randr.h | $(BUILD)
	@[ -n "$(XI_CFLAGS)" ] || echo "WARNING: libxi-dev (pkg-config xi) not found: Super key will not open the Start menu"
	$(CC) -O2 -Wall -Wextra -std=c11 -Isrc $(XI_CFLAGS) $(XRANDR_CFLAGS) -o $@ $(filter %.c,$^) $(XI_LIBS) $(XRANDR_LIBS) \
	    -lX11 -lm
# Built-in screenshot tool (PrtSc / Shift+PrtSc / Alt+PrtSc via hde-hotkeys): no scrot & co. needed
$(BUILD)/hde-screenshot: src/hde-screenshot.c | $(BUILD)
	$(CC) $(GUI_CFLAGS) $(GTK_CFLAGS) $(GLIBX_CFLAGS) $(XFIXES_CFLAGS) -o $@ $< $(GTK_LIBS) $(GLIBX_LIBS) $(XFIXES_LIBS) -lm
# Hyggshi Files (hde-files/): folders, tabs, search, trash, thumbnails, drag and drop; the default file manager of HDE
$(BUILD)/hde-files: $(FILES_SRC) hde-files/src/files.h src/hde-theme.h | $(BUILD)
	$(CC) $(GUI_CFLAGS) -Ihde-files/src -Isrc $(GTK_CFLAGS) -o $@ $(filter %.c,$^) $(GTK_LIBS) -lm
# XSETTINGS (live theme / Dark mode) + touchpad and mouse settings (login, live, hotplug, changes by other programs)
$(BUILD)/hde-xsettings: src/hde-xsettings.c src/hde-input.c src/hde-randr.c src/hde-brightness.c src/hde-input.h \
                        src/hde-randr.h src/hde-brightness.h src/hde-build.h $(VERSION_H) | $(BUILD)
	@[ -n "$(XI_CFLAGS)" ] || echo "WARNING: libxi-dev (pkg-config xi) not found: touchpad/mouse settings will not be applied"
	$(CC) -O2 -Wall -Wextra -std=c11 -Isrc -I$(BUILD) $(GLIBX_CFLAGS) $(XI_CFLAGS) $(XRANDR_CFLAGS) -o $@ $(filter %.c,$^) \
	    $(GLIBX_LIBS) $(XI_LIBS) $(XRANDR_LIBS) -lm
# The screen layouts of F8 without an X server (tests/randr-plan-test.c): run by `make check`
$(BUILD)/randr-plan-test: tests/randr-plan-test.c src/hde-randr.c src/hde-randr.h | $(BUILD)
	$(CC) -O2 -Wall -Wextra -std=c11 -Isrc -o $@ $(filter %.c,$^) -lm
# The SVG path reader that draws the distribution logos of data/logos (tests/svgpath-test.c): run by `make check`
$(BUILD)/svgpath-test: tests/svgpath-test.c src/hde-svgpath.c src/hde-svgpath.h | $(BUILD)
	$(CC) -O2 -Wall -Wextra -std=c11 -Isrc -o $@ $(filter %.c,$^) -lm
# The batteries of src/hde-power.c with fake /sys/class/power_supply trees (tests/power-test.c): run by `make check`
$(BUILD)/power-test: tests/power-test.c src/hde-power.c src/hde-power.h | $(BUILD)
	$(CC) -O2 -Wall -Wextra -std=c11 -Isrc $(GLIBX_CFLAGS) -o $@ $(filter %.c,$^) $(GLIBX_LIBS) -lm
# Measuring the screen and the panel (src/hde-measure.c): the checks without an X server (tests/measure-test.c), run by
# `make check`
$(BUILD)/measure-test: tests/measure-test.c src/hde-measure.c src/hde-measure.h | $(BUILD)
	$(CC) $(GUI_CFLAGS) $(GUI_CPPFLAGS) $(GTK_CFLAGS) $(XRANDR_CFLAGS) -o $@ $(filter %.c,$^) $(GTK_LIBS) $(XRANDR_LIBS) \
	    $(X11_LIBS) -lm
$(BUILD):
	mkdir -p $(BUILD)
$(VERSION_H): FORCE | $(BUILD)
	@sh scripts/hde-version.sh $@
FORCE:
$(BUILD)/hde-core-demo: apps/hde-core-demo.c $(CORE_OBJ) | $(BUILD)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^
$(BUILD)/hde-session: apps/hde-session.c src/hde-wm.h src/hde-build.h $(VERSION_H) $(CORE_OBJ) | $(BUILD)
	$(CC) $(CFLAGS) $(CPPFLAGS) -I$(BUILD) -o $@ $(filter-out %.h,$^)
%.o: %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<
backend/x11/x11_backend.o: src/hde-commands.h
backend/wayland/wayland_backend.o: src/hde-commands.h

# Smoke test: runs a whole HDE session in Xvfb (needs xvfb, xdotool, dbus-x11). See tests/smoke.sh
check: all $(BUILD)/randr-plan-test $(BUILD)/svgpath-test $(BUILD)/power-test $(BUILD)/measure-test
	BUILD=$(BUILD) sh tests/smoke.sh

clean:
	rm -rf $(BUILD) $(CORE_OBJ)
PREFIX ?= /usr/local
XSESSIONS ?= /usr/share/xsessions
WLSESSIONS ?= /usr/share/wayland-sessions
PORTALS_DIR ?= /usr/share/xdg-desktop-portal
APPS_DIR ?= /usr/share/applications

install: all
	install -d $(DESTDIR)$(PREFIX)/bin $(DESTDIR)$(XSESSIONS) $(DESTDIR)$(APPS_DIR)
	install -m755 $(BUILD)/hde-session $(DESTDIR)$(PREFIX)/bin/hde-session
	for b in hde-desktop hde-panel hde-settings hde-hotkeys hde-xsettings hde-screenshot hde-files; do \
	  if [ -x $(BUILD)/$$b ]; then install -m755 $(BUILD)/$$b $(DESTDIR)$(PREFIX)/bin/$$b; \
	  else echo "WARNING: $(BUILD)/$$b missing (libgtk-3-dev / libwnck-3-dev / libxi-dev not installed?)"; fi; done
	install -m755 data/hde-start $(DESTDIR)$(PREFIX)/bin/hde-start
	install -d $(DESTDIR)$(PREFIX)/share/hde/logos $(DESTDIR)$(WLSESSIONS) $(DESTDIR)$(PORTALS_DIR)
	install -m644 data/logos/*.svg data/logos/LICENSES.md $(DESTDIR)$(PREFIX)/share/hde/logos/
	sed 's|@PREFIX@|$(PREFIX)|g' data/hde-wayland.desktop > $(DESTDIR)$(WLSESSIONS)/hde-wayland.desktop
	chmod 644 $(DESTDIR)$(WLSESSIONS)/hde-wayland.desktop
	install -m644 data/hde-portals.conf $(DESTDIR)$(PORTALS_DIR)/hde-portals.conf
	@command -v labwc >/dev/null 2>&1 || echo "NOTE: the HDE (Wayland) session appears on the login screen once labwc is installed (sudo apt install labwc)"
	sed 's|@PREFIX@|$(PREFIX)|g' data/hde.desktop > $(DESTDIR)$(XSESSIONS)/hde.desktop
	sed 's|@PREFIX@|$(PREFIX)|g' data/hyggshi-settings.desktop > $(DESTDIR)$(APPS_DIR)/hyggshi-settings.desktop
	sed 's|@PREFIX@|$(PREFIX)|g' data/hde-screenshot.desktop > $(DESTDIR)$(APPS_DIR)/hde-screenshot.desktop
	sed 's|@PREFIX@|$(PREFIX)|g' hde-files/hde-files.desktop > $(DESTDIR)$(APPS_DIR)/hde-files.desktop
	install -m644 hde-files/hde-mimeapps.list $(DESTDIR)$(APPS_DIR)/hde-mimeapps.list
	chmod 644 $(DESTDIR)$(XSESSIONS)/hde.desktop $(DESTDIR)$(APPS_DIR)/hyggshi-settings.desktop $(DESTDIR)$(APPS_DIR)/hde-screenshot.desktop \
	    $(DESTDIR)$(APPS_DIR)/hde-files.desktop
	-update-desktop-database $(DESTDIR)$(APPS_DIR) 2>/dev/null
# To see a new build WITHOUT LOGGING OUT:
#   make dev                     restart desktop+panel+hotkeys+xsettings from ./build (no install needed)
#   sudo make install && make reload   install into $(PREFIX), then ask hde-session to restart desktop+panel
dev: all
	-pkill -u $$(id -u) -x hde-panel
	-pkill -u $$(id -u) -x hde-desktop
	-pkill -u $$(id -u) -x hde-hotkeys
	-pkill -u $$(id -u) -x hde-xsettings
	sleep 1
	setsid -f $(BUILD)/hde-xsettings
	setsid -f $(BUILD)/hde-hotkeys
	setsid -f $(BUILD)/hde-desktop
	sleep 0.4
	setsid -f $(BUILD)/hde-panel
reload:
	$(PREFIX)/bin/hde-session restart
uninstall:
	for b in $(PROGRAMS) hde-start; do rm -f $(DESTDIR)$(PREFIX)/bin/$$b; done
	rm -f $(DESTDIR)$(XSESSIONS)/hde.desktop $(DESTDIR)$(APPS_DIR)/hyggshi-settings.desktop $(DESTDIR)$(APPS_DIR)/hde-screenshot.desktop
	rm -f $(DESTDIR)$(APPS_DIR)/hde-files.desktop $(DESTDIR)$(APPS_DIR)/hde-mimeapps.list
	rm -rf $(DESTDIR)$(PREFIX)/share/hde
	rm -f $(DESTDIR)$(WLSESSIONS)/hde-wayland.desktop $(DESTDIR)$(PORTALS_DIR)/hde-portals.conf
.PHONY: all clean install uninstall components dev reload check FORCE
