/*
 * nex-settings.cpp - Qt6 GUI Control Panel & Settings for NexWM / NexDE
 */

#include <QApplication>
#include <QWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QTabWidget>
#include <QLabel>
#include <QSpinBox>
#include <QComboBox>
#include <QPushButton>
#include <QLineEdit>
#include <QColorDialog>
#include <QFileDialog>
#include <QMessageBox>
#include <QTableWidget>
#include <QHeaderView>
#include <QPixmap>
#include <QScreen>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>
#include <QProcess>
#include <cstdlib>

struct NexConfig {
    int gaps = 8;
    int workspaceCount = 9;
    QString defaultLayout = "tiled";
    int borderWidth = 2;
    QColor borderFocus = QColor("#5b8dd9");
    QColor borderNormal = QColor("#444444");
    QString wallpaperPath;
    QString wallpaperMode = "scale";
    int desktopIconSize = 48;
};

static QString getConfigPath() {
    const char *home = getenv("HOME");
    if (!home) home = "/root";
    return QString("%1/.config/nexwm/nexwm.conf").arg(home);
}

static NexConfig loadConfig() {
    NexConfig cfg;
    QFile file(getConfigPath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) return cfg;

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith('#')) continue;

        int eqPos = line.indexOf('=');
        if (eqPos == -1) continue;

        QString key = line.left(eqPos).trimmed();
        QString val = line.mid(eqPos + 1).trimmed();

        if (key == "gaps") cfg.gaps = val.toInt();
        else if (key == "workspace_count") cfg.workspaceCount = val.toInt();
        else if (key == "default_layout") cfg.defaultLayout = val;
        else if (key == "border_width") cfg.borderWidth = val.toInt();
        else if (key == "border_focus") cfg.borderFocus = QColor(val);
        else if (key == "border_normal") cfg.borderNormal = QColor(val);
        else if (key == "wallpaper") cfg.wallpaperPath = val;
        else if (key == "wallpaper_mode") cfg.wallpaperMode = val;
        else if (key == "desktop_icon_size") cfg.desktopIconSize = val.toInt();
    }
    file.close();
    return cfg;
}

static bool saveConfig(const NexConfig &cfg) {
    QString path = getConfigPath();
    QFileInfo fi(path);
    QDir().mkpath(fi.absolutePath());

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) return false;

    QTextStream out(&file);
    out << "# NexWM Configuration File\n";
    out << "# Generated by NexSettings Control Panel (Qt6)\n\n";
    out << "gaps = " << cfg.gaps << "\n";
    out << "workspace_count = " << cfg.workspaceCount << "\n";
    out << "default_layout = " << cfg.defaultLayout << "\n";
    out << "border_width = " << cfg.borderWidth << "\n";
    out << "border_focus = " << cfg.borderFocus.name() << "\n";
    out << "border_normal = " << cfg.borderNormal.name() << "\n";
    out << "wallpaper = " << cfg.wallpaperPath << "\n";
    out << "wallpaper_mode = " << cfg.wallpaperMode << "\n";
    out << "desktop_icon_size = " << cfg.desktopIconSize << "\n";
    file.close();
    return true;
}

static void applyIPC(const NexConfig &cfg) {
    QProcess::execute("nexwmctl", {"set-gap", QString::number(cfg.gaps)});
    QProcess::execute("nexwmctl", {"set-layout", cfg.defaultLayout});
    QProcess::execute("nexwmctl", {"workspace-count", QString::number(cfg.workspaceCount)});
    QProcess::execute("nexwmctl", {"reload"});
}

class SettingsWindow : public QWidget {
public:
    SettingsWindow(QWidget *parent = nullptr) : QWidget(parent) {
        setWindowTitle("NexDE Control Panel & Settings");
        resize(540, 520);

        m_cfg = loadConfig();

        auto *mainLayout = new QVBoxLayout(this);
        mainLayout->setSpacing(12);
        mainLayout->setContentsMargins(16, 16, 16, 16);

        // Header Title
        auto *header = new QHBoxLayout();
        auto *title = new QLabel("NexDE Control Panel", this);
        title->setStyleSheet("font-size: 20px; font-weight: bold; color: #5b8dd9;");
        header->addWidget(title);
        header->addStretch();
        mainLayout->addLayout(header);

        // Tab Widget
        m_tabWidget = new QTabWidget(this);
        m_tabWidget->addTab(createAppearanceTab(), "Appearance");
        m_tabWidget->addTab(createDesktopTab(), "Desktop");
        m_tabWidget->addTab(createKeyboardTab(), "Keyboard Shortcuts");
        m_tabWidget->addTab(createDisplayTab(), "Display");
        m_tabWidget->addTab(createAboutTab(), "About NexDE");
        mainLayout->addWidget(m_tabWidget);

        // Bottom Action Buttons
        auto *btnLayout = new QHBoxLayout();
        auto *btnApply = new QPushButton("Apply & Save", this);
        btnApply->setStyleSheet("background-color: #5b8dd9; color: white; font-weight: bold; padding: 8px 18px; border-radius: 6px;");
        connect(btnApply, &QPushButton::clicked, this, &SettingsWindow::onApply);

        auto *btnClose = new QPushButton("Close", this);
        btnClose->setStyleSheet("background-color: #313244; color: #cdd6f4; padding: 8px 18px; border-radius: 6px;");
        connect(btnClose, &QPushButton::clicked, this, &SettingsWindow::close);

        btnLayout->addStretch();
        btnLayout->addWidget(btnClose);
        btnLayout->addWidget(btnApply);
        mainLayout->addLayout(btnLayout);

        // Global Stylesheet
        setStyleSheet(R"(
            QWidget {
                background-color: #1e1e2e;
                color: #cdd6f4;
                font-family: 'Segoe UI', 'Ubuntu', sans-serif;
                font-size: 13px;
            }
            QTabWidget::pane {
                border: 1px solid #313244;
                border-radius: 8px;
                background-color: #181825;
                padding: 12px;
            }
            QTabBar::tab {
                background-color: #181825;
                color: #a6adc8;
                border: 1px solid #313244;
                padding: 8px 16px;
                border-top-left-radius: 6px;
                border-top-right-radius: 6px;
                font-weight: bold;
            }
            QTabBar::tab:selected {
                background-color: #313244;
                color: #ffffff;
                border-bottom-color: #5b8dd9;
            }
            QSpinBox, QComboBox, QLineEdit {
                background-color: #313244;
                color: #cdd6f4;
                border: 1px solid #45475a;
                border-radius: 6px;
                padding: 6px;
            }
            QSpinBox:focus, QComboBox:focus, QLineEdit:focus {
                border: 1px solid #5b8dd9;
            }
            QPushButton {
                background-color: #313244;
                color: #cdd6f4;
                border: 1px solid #45475a;
                border-radius: 6px;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #45475a;
                color: #ffffff;
            }
            QTableWidget {
                background-color: #181825;
                border: 1px solid #313244;
                gridline-color: #313244;
            }
            QHeaderView::section {
                background-color: #313244;
                color: #cdd6f4;
                padding: 6px;
                font-weight: bold;
                border: none;
            }
        )");
    }

private:
    QWidget *createAppearanceTab() {
        auto *w = new QWidget(this);
        auto *form = new QFormLayout(w);
        form->setSpacing(12);

        m_spinGaps = new QSpinBox(w);
        m_spinGaps->setRange(0, 128);
        m_spinGaps->setValue(m_cfg.gaps);
        form->addRow("Window Gaps (px):", m_spinGaps);

        m_spinWorkspaces = new QSpinBox(w);
        m_spinWorkspaces->setRange(1, 9);
        m_spinWorkspaces->setValue(m_cfg.workspaceCount);
        form->addRow("Workspace Count:", m_spinWorkspaces);

        m_comboLayout = new QComboBox(w);
        m_comboLayout->addItems({"tiled", "floating", "monocle"});
        m_comboLayout->setCurrentText(m_cfg.defaultLayout);
        form->addRow("Default Layout Mode:", m_comboLayout);

        m_spinBorderWidth = new QSpinBox(w);
        m_spinBorderWidth->setRange(0, 20);
        m_spinBorderWidth->setValue(m_cfg.borderWidth);
        form->addRow("Border Width (px):", m_spinBorderWidth);

        m_btnFocusColor = new QPushButton(m_cfg.borderFocus.name(), w);
        updateColorButtonStyle(m_btnFocusColor, m_cfg.borderFocus);
        connect(m_btnFocusColor, &QPushButton::clicked, this, [this]() {
            QColor c = QColorDialog::getColor(m_cfg.borderFocus, this, "Select Border Focus Color");
            if (c.isValid()) {
                m_cfg.borderFocus = c;
                m_btnFocusColor->setText(c.name());
                updateColorButtonStyle(m_btnFocusColor, c);
            }
        });
        form->addRow("Border Focus Color:", m_btnFocusColor);

        m_btnNormalColor = new QPushButton(m_cfg.borderNormal.name(), w);
        updateColorButtonStyle(m_btnNormalColor, m_cfg.borderNormal);
        connect(m_btnNormalColor, &QPushButton::clicked, this, [this]() {
            QColor c = QColorDialog::getColor(m_cfg.borderNormal, this, "Select Border Normal Color");
            if (c.isValid()) {
                m_cfg.borderNormal = c;
                m_btnNormalColor->setText(c.name());
                updateColorButtonStyle(m_btnNormalColor, c);
            }
        });
        form->addRow("Border Normal Color:", m_btnNormalColor);

        // Wallpaper row
        auto *bgRow = new QHBoxLayout();
        m_editWallpaper = new QLineEdit(m_cfg.wallpaperPath, w);
        m_editWallpaper->setPlaceholderText("Select wallpaper image file...");
        auto *btnBrowse = new QPushButton("Browse...", w);
        connect(btnBrowse, &QPushButton::clicked, this, [this]() {
            QString file = QFileDialog::getOpenFileName(
                this, "Select Wallpaper Image", QDir::homePath(),
                "Images (*.png *.jpg *.jpeg *.bmp *.webp);;All Files (*)");
            if (!file.isEmpty()) m_editWallpaper->setText(file);
        });
        bgRow->addWidget(m_editWallpaper, 1);
        bgRow->addWidget(btnBrowse);
        form->addRow("Wallpaper File:", bgRow);

        m_comboWallpaperMode = new QComboBox(w);
        m_comboWallpaperMode->addItems({"scale", "stretch", "center", "tile"});
        m_comboWallpaperMode->setCurrentText(m_cfg.wallpaperMode);
        form->addRow("Wallpaper Mode:", m_comboWallpaperMode);

        return w;
    }

    QWidget *createDesktopTab() {
        auto *w = new QWidget(this);
        auto *form = new QFormLayout(w);
        form->setSpacing(14);

        m_spinDesktopIconSize = new QSpinBox(w);
        m_spinDesktopIconSize->setRange(32, 128);
        m_spinDesktopIconSize->setSingleStep(16);
        m_spinDesktopIconSize->setValue(m_cfg.desktopIconSize);
        form->addRow("Desktop Icon Size (px):", m_spinDesktopIconSize);

        auto *lblNote = new QLabel("Desktop icons (Home, Files, Settings, Terminal) are auto-managed by <b>NexDesktop</b>.", w);
        lblNote->setWordWrap(true);
        lblNote->setStyleSheet("color: #a6adc8;");
        form->addRow(lblNote);

        return w;
    }

    QWidget *createKeyboardTab() {
        auto *w = new QWidget(this);
        auto *layout = new QVBoxLayout(w);

        auto *table = new QTableWidget(7, 2, w);
        table->setHorizontalHeaderLabels({"Shortcut Key", "Action"});
        table->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);

        struct Binding { const char *key; const char *desc; };
        Binding bindings[] = {
            {"Super + Enter", "Launch NexTerminal"},
            {"Super + D", "Launch Application Launcher (Spotlight)"},
            {"Super + Q", "Close Focused Window"},
            {"Super + Space", "Toggle Floating Window Layout"},
            {"Super + 1..9", "Switch to Virtual Workspace 1..9"},
            {"Super + Shift + 1..9", "Move Focused Window to Workspace 1..9"},
            {"Super + Shift + Escape", "Exit NexWM Session"}
        };

        for (int i = 0; i < 7; i++) {
            table->setItem(i, 0, new QTableWidgetItem(bindings[i].key));
            table->setItem(i, 1, new QTableWidgetItem(bindings[i].desc));
        }

        layout->addWidget(table);
        return w;
    }

    QWidget *createDisplayTab() {
        auto *w = new QWidget(this);
        auto *layout = new QVBoxLayout(w);
        layout->setSpacing(12);

        QScreen *screen = QGuiApplication::primaryScreen();
        QString screenInfo = "No screen detected";
        if (screen) {
            QRect geom = screen->geometry();
            screenInfo = QString("<b>Primary Display:</b> %1x%2 @ %3 Hz<br><b>Name:</b> %4")
                .arg(geom.width()).arg(geom.height())
                .arg(qRound(screen->refreshRate()))
                .arg(screen->name());
        }

        auto *lbl = new QLabel(screenInfo, w);
        lbl->setStyleSheet("font-size: 14px; color: #cdd6f4; line-height: 1.5;");
        layout->addWidget(lbl);

        auto *infoText = new QLabel("Multi-monitor support is powered by XRandR in NexWM. Use <b>xrandr</b> CLI or connect external displays for automatic extension.", w);
        infoText->setWordWrap(true);
        infoText->setStyleSheet("color: #a6adc8;");
        layout->addWidget(infoText);
        layout->addStretch();

        return w;
    }

    QWidget *createAboutTab() {
        auto *w = new QWidget(this);
        auto *layout = new QVBoxLayout(w);
        layout->setSpacing(10);

        auto *lblTitle = new QLabel("Nex Desktop Environment", w);
        lblTitle->setStyleSheet("font-size: 18px; font-weight: bold; color: #5b8dd9;");
        layout->addWidget(lblTitle);

        auto *lblDesc = new QLabel(
            "<b>Version:</b> 0.1.0 (Developer Preview)<br>"
            "<b>Architecture:</b> X11 / XCB + Qt6<br>"
            "<b>Ecosystem:</b> Hyggshi OS / Nex Suite<br><br>"
            "<b>Components:</b><br>"
            "• <b>NexWM</b>: Lightweight C11 Window Manager<br>"
            "• <b>NexPanel</b>: XCB Status Bar & Taskbar with PNG icons<br>"
            "• <b>NexDesktop</b>: XCB Desktop Surface & Icon Grid<br>"
            "• <b>NexLauncher</b>: Spotlight Application Launcher<br>"
            "• <b>NexFM</b>: Qt6 File Manager<br>"
            "• <b>NexTerminal</b>: Qt6 Terminal Emulator<br>"
            "• <b>NexSettings</b>: Control Panel", w);
        lblDesc->setStyleSheet("line-height: 1.4; color: #cdd6f4;");
        layout->addWidget(lblDesc);
        layout->addStretch();

        return w;
    }

    void updateColorButtonStyle(QPushButton *btn, const QColor &c) {
        btn->setStyleSheet(QString("background-color: %1; color: %2; font-weight: bold; border: 1px solid #45475a; border-radius: 6px; padding: 6px;")
                           .arg(c.name(), (c.lightness() > 128) ? "#000000" : "#ffffff"));
    }

    void onApply() {
        m_cfg.gaps = m_spinGaps->value();
        m_cfg.workspaceCount = m_spinWorkspaces->value();
        m_cfg.defaultLayout = m_comboLayout->currentText();
        m_cfg.borderWidth = m_spinBorderWidth->value();
        m_cfg.wallpaperPath = m_editWallpaper->text().trimmed();
        m_cfg.wallpaperMode = m_comboWallpaperMode->currentText();
        m_cfg.desktopIconSize = m_spinDesktopIconSize->value();

        /*
         * Validate wallpaper before changing anything.
         */
        if (!m_cfg.wallpaperPath.isEmpty()) {
            QFileInfo info(m_cfg.wallpaperPath);

            if (!info.exists() || !info.isFile()) {
                QMessageBox::warning(
                    this,
                    "NexSettings",
                    QString("Wallpaper image file not found:\n%1")
                        .arg(m_cfg.wallpaperPath)
                );
                return;
            }

            if (!info.isReadable()) {
                QMessageBox::warning(
                    this,
                    "NexSettings",
                    QString("Wallpaper image is not readable:\n%1")
                        .arg(m_cfg.wallpaperPath)
                );
                return;
            }
        }

        /*
         * Save the complete configuration first.
         */
        if (!saveConfig(m_cfg)) {
            QMessageBox::critical(
                this,
                "NexSettings",
                "Failed to save configuration file."
            );
            return;
        }

        /*
         * Apply wallpaper using Qt's QProcess.
         *
         * nex-settings is a Qt6 application. No GTK API is used here and
         * no child widget is manually hidden/destroyed.
         */
        if (!m_cfg.wallpaperPath.isEmpty()) {
            QProcess wallpaper;

            wallpaper.setProgram("nex-wallpaper");
            wallpaper.setArguments({
                "--set",
                m_cfg.wallpaperPath,
                "--mode",
                m_cfg.wallpaperMode
            });

            wallpaper.start();

            if (!wallpaper.waitForStarted(3000)) {
                QMessageBox::warning(
                    this,
                    "NexSettings",
                    QString("Failed to start nex-wallpaper:\n%1")
                        .arg(wallpaper.errorString())
                );
                return;
            }

            if (!wallpaper.waitForFinished(15000)) {
                wallpaper.kill();
                wallpaper.waitForFinished(2000);

                QMessageBox::warning(
                    this,
                    "NexSettings",
                    "nex-wallpaper did not finish within 15 seconds."
                );
                return;
            }

            const QByteArray stderrData =
                wallpaper.readAllStandardError();

            const QByteArray stdoutData =
                wallpaper.readAllStandardOutput();

            if (wallpaper.exitStatus() != QProcess::NormalExit ||
                wallpaper.exitCode() != 0) {

                QString details =
                    QString::fromLocal8Bit(stderrData).trimmed();

                if (details.isEmpty()) {
                    details =
                        QString::fromLocal8Bit(stdoutData).trimmed();
                }

                if (details.isEmpty()) {
                    details = "nex-wallpaper exited with an error.";
                }

                QMessageBox::warning(
                    this,
                    "NexSettings",
                    QString(
                        "Failed to apply wallpaper.\n\n"
                        "Exit code: %1\n"
                        "%2"
                    )
                    .arg(wallpaper.exitCode())
                    .arg(details)
                );
                return;
            }
        }

        /*
         * Apply NexWM IPC settings.
         */
        applyIPC(m_cfg);

        QMessageBox::information(
            this,
            "NexSettings",
            "Settings applied and saved successfully!"
        );
    }

    NexConfig m_cfg;
    QTabWidget *m_tabWidget;

    /* Appearance */
    QSpinBox *m_spinGaps;
    QSpinBox *m_spinWorkspaces;
    QComboBox *m_comboLayout;
    QSpinBox *m_spinBorderWidth;
    QPushButton *m_btnFocusColor;
    QPushButton *m_btnNormalColor;
    QLineEdit *m_editWallpaper;
    QComboBox *m_comboWallpaperMode;

    /* Desktop */
    QSpinBox *m_spinDesktopIconSize;
};

int main(int argc, char **argv) {
    QApplication app(argc, argv);
    SettingsWindow win;
    win.show();
    return app.exec();
}
