/*
 * nex-settings.cpp - Qt6 GUI Control Panel & Settings for NexWM
 */

#include <QApplication>
#include <QWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QLabel>
#include <QSpinBox>
#include <QComboBox>
#include <QPushButton>
#include <QColorDialog>
#include <QMessageBox>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QProcess>
#include <cstdlib>

struct NexConfig {
    int gaps = 8;
    int workspaceCount = 9;
    QString defaultLayout = "tiled";
    int borderWidth = 2;
    QColor borderFocus = QColor("#5b8dd9");
    QColor borderNormal = QColor("#444444");
};

static QString getConfigPath() {
    const char *home = getenv("HOME");
    if (!home) home = "/root";
    return QString("%1/.config/nexwm/nexwm.conf").arg(home);
}

static NexConfig loadConfig() {
    NexConfig cfg;
    QFile file(getConfigPath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) return cfg;

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith('#')) continue;

        int eqPos = line.indexOf('=');
        if (eqPos == -1) continue;

        QString key = line.left(eqPos).trimmed();
        QString val = line.mid(eqPos + 1).trimmed();

        if (key == "gaps") cfg.gaps = val.toInt();
        else if (key == "workspace_count") cfg.workspaceCount = val.toInt();
        else if (key == "default_layout") cfg.defaultLayout = val;
        else if (key == "border_width") cfg.borderWidth = val.toInt();
        else if (key == "border_focus") cfg.borderFocus = QColor(val);
        else if (key == "border_normal") cfg.borderNormal = QColor(val);
    }
    file.close();
    return cfg;
}

static bool saveConfig(const NexConfig &cfg) {
    QString path = getConfigPath();
    QFileInfo fi(path);
    QDir().mkpath(fi.absolutePath());

    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) return false;

    QTextStream out(&file);
    out << "# NexWM Configuration File\n";
    out << "# Generated by NexSettings (Qt6)\n\n";
    out << "gaps = " << cfg.gaps << "\n";
    out << "workspace_count = " << cfg.workspaceCount << "\n";
    out << "default_layout = " << cfg.defaultLayout << "\n";
    out << "border_width = " << cfg.borderWidth << "\n";
    out << "border_focus = " << cfg.borderFocus.name() << "\n";
    out << "border_normal = " << cfg.borderNormal.name() << "\n";
    file.close();
    return true;
}

static void applyIPC(const NexConfig &cfg) {
    QProcess::execute("nexwmctl", {"set-gap", QString::number(cfg.gaps)});
    QProcess::execute("nexwmctl", {"set-layout", cfg.defaultLayout});
    QProcess::execute("nexwmctl", {"workspace-count", QString::number(cfg.workspaceCount)});
    QProcess::execute("nexwmctl", {"reload"});
}

class SettingsWindow : public QWidget {
public:
    SettingsWindow(QWidget *parent = nullptr) : QWidget(parent) {
        setWindowTitle("NexWM Settings Control Panel");
        resize(420, 360);

        m_cfg = loadConfig();

        auto *mainLayout = new QVBoxLayout(this);
        mainLayout->setSpacing(15);
        mainLayout->setContentsMargins(20, 20, 20, 20);

        auto *title = new QLabel("NexWM Settings", this);
        title->setStyleSheet("font-size: 18px; font-weight: bold; color: #5b8dd9;");
        mainLayout->addWidget(title);

        auto *form = new QFormLayout();
        form->setSpacing(12);

        m_spinGaps = new QSpinBox(this);
        m_spinGaps->setRange(0, 128);
        m_spinGaps->setValue(m_cfg.gaps);
        form->addRow("Window Gaps (px):", m_spinGaps);

        m_spinWorkspaces = new QSpinBox(this);
        m_spinWorkspaces->setRange(1, 9);
        m_spinWorkspaces->setValue(m_cfg.workspaceCount);
        form->addRow("Workspace Count:", m_spinWorkspaces);

        m_comboLayout = new QComboBox(this);
        m_comboLayout->addItems({"tiled", "floating", "monocle"});
        m_comboLayout->setCurrentText(m_cfg.defaultLayout);
        form->addRow("Default Layout:", m_comboLayout);

        m_spinBorderWidth = new QSpinBox(this);
        m_spinBorderWidth->setRange(0, 20);
        m_spinBorderWidth->setValue(m_cfg.borderWidth);
        form->addRow("Border Width (px):", m_spinBorderWidth);

        m_btnFocusColor = new QPushButton(m_cfg.borderFocus.name(), this);
        updateColorButtonStyle(m_btnFocusColor, m_cfg.borderFocus);
        connect(m_btnFocusColor, &QPushButton::clicked, this, [this]() {
            QColor c = QColorDialog::getColor(m_cfg.borderFocus, this, "Select Focus Border Color");
            if (c.isValid()) {
                m_cfg.borderFocus = c;
                m_btnFocusColor->setText(c.name());
                updateColorButtonStyle(m_btnFocusColor, c);
            }
        });
        form->addRow("Border Focus Color:", m_btnFocusColor);

        m_btnNormalColor = new QPushButton(m_cfg.borderNormal.name(), this);
        updateColorButtonStyle(m_btnNormalColor, m_cfg.borderNormal);
        connect(m_btnNormalColor, &QPushButton::clicked, this, [this]() {
            QColor c = QColorDialog::getColor(m_cfg.borderNormal, this, "Select Normal Border Color");
            if (c.isValid()) {
                m_cfg.borderNormal = c;
                m_btnNormalColor->setText(c.name());
                updateColorButtonStyle(m_btnNormalColor, c);
            }
        });
        form->addRow("Border Normal Color:", m_btnNormalColor);

        mainLayout->addLayout(form);

        auto *btnLayout = new QHBoxLayout();
        auto *btnApply = new QPushButton("Apply & Save", this);
        btnApply->setStyleSheet("background-color: #5b8dd9; color: white; font-weight: bold; padding: 8px 16px; border-radius: 4px;");
        connect(btnApply, &QPushButton::clicked, this, &SettingsWindow::onApply);

        auto *btnClose = new QPushButton("Close", this);
        btnClose->setStyleSheet("background-color: #333; color: white; padding: 8px 16px; border-radius: 4px;");
        connect(btnClose, &QPushButton::clicked, this, &SettingsWindow::close);

        btnLayout->addStretch();
        btnLayout->addWidget(btnClose);
        btnLayout->addWidget(btnApply);
        mainLayout->addLayout(btnLayout);

        setStyleSheet(R"(
            QWidget {
                background-color: #1e1e2e;
                color: #cdd6f4;
                font-size: 13px;
            }
            QSpinBox, QComboBox {
                background-color: #313244;
                color: #cdd6f4;
                border: 1px solid #45475a;
                border-radius: 4px;
                padding: 4px;
            }
            QPushButton {
                background-color: #313244;
                color: #cdd6f4;
                border: 1px solid #45475a;
                border-radius: 4px;
                padding: 6px;
            }
            QPushButton:hover {
                background-color: #45475a;
            }
        )");
    }

private:
    void updateColorButtonStyle(QPushButton *btn, const QColor &c) {
        btn->setStyleSheet(QString("background-color: %1; color: %2; font-weight: bold; border: 1px solid #45475a; border-radius: 4px; padding: 6px;")
                           .arg(c.name(), (c.lightness() > 128) ? "#000000" : "#ffffff"));
    }

    void onApply() {
        m_cfg.gaps = m_spinGaps->value();
        m_cfg.workspaceCount = m_spinWorkspaces->value();
        m_cfg.defaultLayout = m_comboLayout->currentText();
        m_cfg.borderWidth = m_spinBorderWidth->value();

        if (saveConfig(m_cfg)) {
            applyIPC(m_cfg);
            QMessageBox::information(this, "NexWM Settings", "Settings applied and saved successfully!");
        } else {
            QMessageBox::critical(this, "NexWM Settings", "Failed to save configuration file.");
        }
    }

    NexConfig m_cfg;
    QSpinBox *m_spinGaps;
    QSpinBox *m_spinWorkspaces;
    QComboBox *m_comboLayout;
    QSpinBox *m_spinBorderWidth;
    QPushButton *m_btnFocusColor;
    QPushButton *m_btnNormalColor;
};

int main(int argc, char **argv) {
    QApplication app(argc, argv);
    SettingsWindow win;
    win.show();
    return app.exec();
}
