#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif

/*
 * nex-settings.c - NexSettings
 * Settings Control Panel for NexWM / Hyggshi OS
 *
 * Reads/writes ~/.config/nexwm/nexwm.conf and applies live changes
 * via nexwmctl IPC calls (set-gap, set-layout, workspace-count, reload).
 */

#include "nex-settings.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>

static void get_default_config_path(char *buf, size_t bufsz)
{
    const char *home = getenv("HOME");
    if (!home) home = "/root";
    snprintf(buf, bufsz, "%s/.config/nexwm/nexwm.conf", home);
}

int nex_settings_load(nex_settings_t *s, const char *path)
{
    if (!s) return -1;
    memset(s, 0, sizeof(*s));

    /* Default values */
    s->gaps = 8;
    s->workspace_count = 9;
    strncpy(s->default_layout, "tiled", sizeof(s->default_layout) - 1);
    s->border_width = 2;
    s->border_focus = 0x5b8dd9;
    s->border_normal = 0x444444;

    char default_path[512];
    if (!path || path[0] == '\0') {
        get_default_config_path(default_path, sizeof(default_path));
        path = default_path;
    }

    FILE *f = fopen(path, "r");
    if (!f) return 0; /* use defaults if file not present */

    char line[512];
    while (fgets(line, sizeof(line), f)) {
        size_t len = strlen(line);
        if (len > 0 && line[len - 1] == '\n') line[len - 1] = '\0';
        if (line[0] == '#' || line[0] == '\0') continue;

        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';

        char *key = line;
        char *val = eq + 1;

        /* Trim leading/trailing whitespace */
        while (*key == ' ') key++;
        while (*val == ' ') val++;

        if (strcmp(key, "gaps") == 0) {
            s->gaps = atoi(val);
        } else if (strcmp(key, "workspace_count") == 0) {
            s->workspace_count = atoi(val);
        } else if (strcmp(key, "default_layout") == 0) {
            strncpy(s->default_layout, val, sizeof(s->default_layout) - 1);
        } else if (strcmp(key, "border_width") == 0) {
            s->border_width = atoi(val);
        } else if (strcmp(key, "border_focus") == 0) {
            s->border_focus = (unsigned int)strtoul(val, NULL, 0);
        } else if (strcmp(key, "border_normal") == 0) {
            s->border_normal = (unsigned int)strtoul(val, NULL, 0);
        }
    }

    fclose(f);
    return 0;
}

int nex_settings_save(const nex_settings_t *s, const char *path)
{
    if (!s) return -1;

    char default_path[512];
    if (!path || path[0] == '\0') {
        get_default_config_path(default_path, sizeof(default_path));
        path = default_path;
    }

    /* Ensure directory ~/.config/nexwm exists */
    char dir[512];
    strncpy(dir, path, sizeof(dir) - 1);
    char *last_slash = strrchr(dir, '/');
    if (last_slash) {
        *last_slash = '\0';
        mkdir(dir, 0755);
    }

    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "nex-settings: failed to write to %s: %s\n", path, strerror(errno));
        return -1;
    }

    fprintf(f, "# NexWM Configuration File\n");
    fprintf(f, "# Auto-generated by NexSettings\n\n");
    fprintf(f, "gaps = %d\n", s->gaps);
    fprintf(f, "workspace_count = %d\n", s->workspace_count);
    fprintf(f, "default_layout = %s\n", s->default_layout);
    fprintf(f, "border_width = %d\n", s->border_width);
    fprintf(f, "border_focus = 0x%06x\n", s->border_focus);
    fprintf(f, "border_normal = 0x%06x\n", s->border_normal);

    fclose(f);
    printf("Saved settings to %s\n", path);
    return 0;
}

int nex_settings_apply_ipc(const nex_settings_t *s)
{
    if (!s) return -1;

    char cmd[256];

    snprintf(cmd, sizeof(cmd), "nexwmctl set-gap %d", s->gaps);
    system(cmd);

    snprintf(cmd, sizeof(cmd), "nexwmctl set-layout %s", s->default_layout);
    system(cmd);

    snprintf(cmd, sizeof(cmd), "nexwmctl workspace-count %d", s->workspace_count);
    system(cmd);

    system("nexwmctl reload");
    return 0;
}

int main(int argc, char **argv)
{
    nex_settings_t s;
    nex_settings_load(&s, NULL);

    if (argc > 1) {
        for (int i = 1; i < argc; i++) {
            if (strcmp(argv[i], "--set-gap") == 0 && i + 1 < argc) {
                s.gaps = atoi(argv[++i]);
            } else if (strcmp(argv[i], "--set-layout") == 0 && i + 1 < argc) {
                strncpy(s.default_layout, argv[++i], sizeof(s.default_layout) - 1);
            } else if (strcmp(argv[i], "--set-workspaces") == 0 && i + 1 < argc) {
                s.workspace_count = atoi(argv[++i]);
            }
        }
        nex_settings_save(&s, NULL);
        nex_settings_apply_ipc(&s);
        return 0;
    }

    printf("=== NexSettings Control Panel ===\n");
    printf("Current Configuration:\n");
    printf("  Gaps:            %d px\n", s.gaps);
    printf("  Workspaces:      %d\n", s.workspace_count);
    printf("  Default Layout:  %s\n", s.default_layout);
    printf("  Border Width:    %d px\n", s.border_width);
    printf("  Border Focus:    0x%06x\n", s.border_focus);
    printf("  Border Normal:   0x%06x\n", s.border_normal);
    printf("\nUsage to update:\n");
    printf("  nex-settings --set-gap <pixels> --set-layout <tiled|floating|monocle> --set-workspaces <count>\n");
    return 0;
}
